export const categories = [
  {
    id: 1,
    title: 'Bath Robes',
    subtitle: 'Wrap & Unwind',
    image: '/category_cotton_1770900530532.png',
    description: 'Plush, absorbent bath robes that turn every morning into a spa ritual.',
    productCount: 3,
  },
  {
    id: 2,
    title: 'Hair Towels',
    subtitle: 'Gentle Drying',
    image: '/category_filament_1770900548571.png',
    description: 'Ultra-absorbent, frizz-free hair towels and wraps for healthier hair.',
    productCount: 3,
  },
  {
    id: 3,
    title: 'Bath Towels',
    subtitle: 'Everyday Luxury',
    image: '/category_mixed_1770900596346.png',
    description: 'Soft, quick-drying bath towels crafted for daily indulgence.',
    productCount: 3,
  },
  {
    id: 4,
    title: 'Adult Towels',
    subtitle: 'Premium & Durable',
    image: '/category_carbon_1770900631300.png',
    description: 'Generously sized premium towels built for lasting comfort and durability.',
    productCount: 3,
  },
  {
    id: 5,
    title: 'Kids & Infant Care',
    subtitle: 'Soft & Safe',
    image: '/emerald_cotton_towel_1770901516592.png',
    description: 'Hypoallergenic, chemical-free towels designed for delicate young skin.',
    productCount: 3,
  },
];
